export type {
  KnowgoWorkspace,
  KnowgoProject,
  ProjectBrief,
  InspirationCapture,
  UrlParseResult,
  ImageAnalysis,
  VideoAnalysis,
  StoryboardShot,
  InspirationDocument,
  DocumentSection,
  StyleGuide,
  FontRecommendation,
  VfxRecommendation,
  SimilarShort,
} from "@everec/shared";
